volumes:
  db_data:
  uploads:

services:
  app:
    image: cookbook-api:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./Public:/app/Public
    restart: unless-stopped
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: cookbook-api:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: cookbook-api:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: raynelz
      POSTGRES_PASSWORD: syrVak-dyhnig-pimnu1
      POSTGRES_DB: cookbook_production
    ports:
      - '5432:5432'
    restart: unless-stopped